### ISSUE TITLE
Bool variables are rendered as 0 or 1

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.docs#15]
When a variable is a bool and rendered in a Xentriq template, it is output as a 0 or 1 instead of true or false.

**Comment by mpwaldhorst** [comment]
Not sure, thought the same but maybe good to check?

**Comment by ttveldhuis** [comment]
This has been updated in xentriq.core/version_1_0. Booleans are now rendered as 'true' or 'false'.
