### ISSUE TITLE
Add documentation for environment specific configuration.

### ISSUE THREAD

**Issue by ttveldhuis** [Nentix/xentriq.docs#23]
Add documentation for environment specific configuration. See https://github.com/Nentix/xentriq.core/issues/48

**Comment by mpwaldhorst** [comment]
@ttveldhuis maybe we should change the title here to be about adding documentation about configuration in general? The current documentation is a bit basic.

**Comment by mpwaldhorst** [comment]
Or maybe seeing that this is target for 1.0 maybe we should have a separate one for that?
